FROM node:22-alpine

# Instalar FFmpeg y FFprobe nativos
RUN apk add --no-cache ffmpeg

WORKDIR /app

# Instalar dependencias de producción
COPY package*.json ./
RUN npm ci

# Copiar el código fuente
COPY . .

CMD ["node", "src/index.js"]