version: '3.8'

volumes:
  storage:
    driver: local

networks:
  proxy:
    driver: bridge

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: worker-app
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis-studio
      - REDIS_PORT=6379
    volumes:
      - .:/app
      - /app/node_modules
      - storage:/app/storage
    command: npm run dev
    networks:
      - proxy
    deploy:
      resources:
        limits:
          cpus: '3.0'
          memory: 6G

